{
 "title": "BOSH: Updates",
 "tags": [ "bosh" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(boshupdate_deployment_status, environment)"
   }
  ]
 },
 "panels": [
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Out-of-date",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(time() - label_replace(\n  label_replace(\n    min_over_time(boshupdate_deployment_status{environment=~\"$environment\"}[2h]) > 0,\n    \"_01_manifest\", \"$1\", \"name\", \"(.*)\"),\n  \"_02_deployment\", \"$1\", \"deployment\", \"(.*)\"))\n  / 86400"
    }
   ]
  },
  {
   "title": "Not monitored",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n    min_over_time(boshupdate_deployment_status{environment=~\"$environment\", latest=\"not-found\"}[30m]) == 0,\n    \"_01_manifest\", \"$1\", \"name\", \"(.*)\"),\n  \"_02_deployment\", \"$1\", \"deployment\", \"(.*)\")\n  * 1000"
    }
   ]
  },
  {
   "title": "Up-to-date",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n    min_over_time(boshupdate_deployment_status{environment=~\"$environment\", latest!=\"not-found\"}[2h]) == 0,\n    \"_01_manifest\", \"$1\", \"name\", \"(.*)\"),\n  \"_02_deployment\", \"$1\", \"deployment\", \"(.*)\")\n  * 1000"
    }
   ]
  },
  { "title": "Deployment Releases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Out-of-date",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "(time() - \nlabel_replace(\n  label_replace(\n    label_replace(\n      min_over_time(boshupdate_deployment_bosh_release_status{environment=~\"$environment\"}[2h]) > 0,\n      \"_02_manifest\",   \"$1\", \"manifest_name\", \"(.*)\"),\n    \"_03_boshrelease\",\"$1\", \"boshrelease_name\", \"(.*)\"),\n  \"_01_deployment\", \"$1\", \"deployment\",    \"(.*)\"))\n  / 86400"
    }
   ]
  },
  {
   "title": "Not monitored",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n    label_replace(\n      min_over_time(boshupdate_deployment_bosh_release_status{environment=~\"$environment\", boshrelease_latest=\"not-found\"}[2h]) == 0,\n      \"_02_manifest\",   \"$1\", \"manifest_name\", \"(.*)\"),\n    \"_03_boshrelease\",\"$1\", \"boshrelease_name\", \"(.*)\"),\n  \"_01_deployment\", \"$1\", \"deployment\",    \"(.*)\")\n* 1000"
    }
   ]
  },
  {
   "title": "Up-to-date",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n    label_replace(\n      min_over_time(boshupdate_deployment_bosh_release_status{environment=~\"$environment\", boshrelease_latest!=\"not-found\"}[2h]) == 0,\n      \"_02_manifest\",   \"$1\", \"manifest_name\", \"(.*)\"),\n    \"_03_boshrelease\",\"$1\", \"boshrelease_name\", \"(.*)\"),\n  \"_01_deployment\", \"$1\", \"deployment\",    \"(.*)\")\n  * 1000"
    }
   ]
  },
  { "title": "Canonical Manifests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Canonical manifests",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "label_replace(\n  min_over_time(boshupdate_manifest_release{environment=~\"$environment\"}[30m]) == 0,\n  \"_01_name\", \"$1\", \"name\", \"(.*)\")"
    }
   ]
  },
  {
   "title": "Bosh releases",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n    max_over_time(boshupdate_manifest_bosh_release_info{environment=~\"$environment\"}[30m]),\n    \"_01_manifest_name\", \"$1\", \"manifest_name\", \"(.*)\"),\n  \"_02_manifest_version\", \"$1\", \"manifest_version\", \"(.*)\")\n"
    }
   ]
  },
  { "title": "Scrapping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Scrape duration (ms)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "boshupdate_last_scrape_duration",
     "legendFormat": "{{site}}/{{environment}}/{{job}}"
    }
   ]
  },
  {
   "title": "Scrape Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "boshupdate_last_scrape_error",
     "legendFormat": "{{site}}/{{environment}}/{{job}}"
    }
   ]
  }
 ]
}